version: "3.7"

services:
  postgres:
    image: postgres
    container_name: my_postgres_db
    ports:
      - "5450:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
